services:
  pool:
    build: .
    restart: always
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    ports:
      - 0.0.0.0:18888:18888
  redis:
    image: redis:latest
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
